### ISSUE TITLE
 Problem during installation

### ISSUE THREAD

**Issue by lagrezd** [cogniteev/oncrawl-elk#13]
ERROR: failed to register layer: devmapper: Error mounting '/dev/mapper/docker-9:2-1051856-27a2b88e520cd62629c407144a97a05a13eb9c8f0b70bdf322821038364a3f7b' on '/var/lib/docker/devicemapper/mnt/27a2b88e520cd62629c407144a97a05a13eb9c8f0b70bdf322821038364a3f7b': invalid argument
Do you have an idea ?
Environment : ubuntu 16.04, docker 1.12.1 and docker-compose 1.8.0

**Comment by tuxnco** [comment]
Issue with docker installation, closing.
