### ISSUE TITLE
how to purge all logs???

### ISSUE THREAD

**Issue by pioc92** [cogniteev/oncrawl-elk#15]
Hi, could you help me to purge all my logs?

I also try to test the doc command line to limit to most recent 100gb logs : 
docker run --rm --link oncrawlelk_elasticsearch_1:elasticsearch digitalwonderland/elasticsearch-curator --host elasticsearch -n delete --disk-space 100 

error: no such option n

**Comment by tuxnco** [comment]
If you can't get elasticsearch-curator working, at last you could purge your elasticsearch image.
