### ISSUE TITLE
No logs found

### ISSUE THREAD

**Issue by RobinHerzog** [cogniteev/oncrawl-elk#17]
Hi,

How to import logs into this tools ? I can't find an directory into the docker file. I'm using Apache & Nginx.

**Comment by tuxnco** [comment]
Hi,
As you can see here: https://github.com/cogniteev/oncrawl-elk/blob/master/docker-compose.yml#L16 the logs directory from current working directory is mounted into logstash's container.
Simply put your logs and they should become available any time soon.
Hope the helps!

**Comment by RobinHerzog** [comment]
Est-ce que ça veut dire que je dois créer un dossier /logs à la racine de mon linux ?

**Comment by tuxnco** [comment]
No, the `logs` directory from your local filesystem is mounted at the root `/logs` directory in the container where logstash reads the logs from either `/logs/nginx/`, `/logs/apache/` or `/logs/iis/`.
You should therefor drop your logs in corresponding local directory (ie `logs/nginx/` if you use nginx).
Read the docker-compose.yml file for the details.

**Comment by RobinHerzog** [comment]
Thanks it works ! I went directly into the logstash and downloaded the logs
